/**
 * Service worker for the installable app.
 *
 * Written by hand rather than generated by Workbox. Workbox writes
 * absolute local import paths into the service worker it generates,
 * and this project's folder name contains an apostrophe, which closes
 * the string literal and produces a file that will not parse. The
 * caching policy here is simple enough that owning it outright costs
 * less than working around that.
 *
 * The policy in one line: cache the application shell, never cache
 * the data.
 */

// Replaced at build time with every hashed asset in dist/.
const MANIFEST = self.__WB_MANIFEST ?? []
const ASSETS = ['/', ...MANIFEST.map((entry) => entry.url ?? entry)]

// Asset filenames are content-hashed, so the joined revision list
// changes whenever anything in the build changes. That gives each
// deploy its own cache without a version number to remember to bump.
const VERSION = MANIFEST.map((e) => e.revision ?? e.url ?? e)
  .join('|')
  .length.toString(36)
const CACHE = `davric-vms-${VERSION}`

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(ASSETS))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith('davric-vms-') && name !== CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  )
})

// The update prompt in the app sends this when the user accepts.
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  const url = new URL(request.url)

  // Never touch the database. A cached visitor list would show someone
  // as still on the premises after they left, and a cached auth
  // response is worse. Let these fail loudly when offline -- the app
  // shows its own "no connection" banner.
  if (url.hostname.endsWith('.supabase.co')) return

  // Navigations: try the network so a deployed update is picked up,
  // fall back to the cached shell when there is no connection. The
  // app then renders and reports itself offline, rather than the
  // browser showing a dinosaur.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(
        async () =>
          (await caches.match('/index.html')) ??
          (await caches.match('/')) ??
          Response.error(),
      ),
    )
    return
  }

  // Everything else is a hashed asset or a font: cache first.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok && (url.origin === self.location.origin ||
                              url.hostname.endsWith('gstatic.com') ||
                              url.hostname.endsWith('googleapis.com'))) {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        }),
    ),
  )
})
